In [ ]:
"""
mongodb+srv://sarnab17:Sarnab@2002@cluster0.f0rnzlp.mongodb.net/?appName=Cluster0
"""

'\nmongodb+srv://sarnab17:Sarnab@2002@cluster0.f0rnzlp.mongodb.net/?appName=Cluster0\n'

In [27]:
import pandas as pd
from urllib.parse import quote_plus
from pymongo import MongoClient

In [3]:
df = pd.read_csv('Data/EasyVisa.csv')
len(df)

25480

In [4]:
df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [6]:
df.shape

(25480, 12)

In [7]:
df.columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [9]:
data = df.to_dict(orient='records')
data[0]

{'case_id': 'EZYV01',
 'continent': 'Asia',
 'education_of_employee': 'High School',
 'has_job_experience': 'N',
 'requires_job_training': 'N',
 'no_of_employees': 14513,
 'yr_of_estab': 2007,
 'region_of_employment': 'West',
 'prevailing_wage': 592.2029,
 'unit_of_wage': 'Hour',
 'full_time_position': 'Y',
 'case_status': 'Denied'}

In [10]:
len(data)

25480

In [38]:
username = "sarnab17"
password = quote_plus("Sarnab@2002")

In [39]:
DB_NAME = 'US_Visa'
COLLECTION_NAME = 'Visa_Data'
CONNECTION_STRING = f"mongodb+srv://{username}:{password}@cluster0.f0rnzlp.mongodb.net/?appName=Cluster0"

In [40]:
client = MongoClient(CONNECTION_STRING)
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]

rec = collection.insert_many(data)

##### TimeOut Error can be resolved using the certifi library

```python

import certifi
client = pymongo.MongoClient(CONNECTION_URL, tlsCAFile=certifi.where())
# TO CREATE THE DATABASE
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]
# TO INSERT DATA INTO THE COLLECTION
rec = collection.insert_many(data)
```

In [46]:
records = collection.find()
print(records)

<pymongo.synchronous.cursor.Cursor object at 0x00000293BCAD9520>

In [47]:
df = pd.DataFrame(list(records))

In [50]:
if "_id" in df.columns.to_list():
    df.drop(columns=["_id"], inplace=True)

In [52]:
df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified